spring : 
  jpa : 
    show-sql : true
    hibernate : 
      ddl-auto : 
  
  thymeleaf : 
    cache : false

  datasource : 
    url : jdbc:mysql://localhost:3306/essai_cantine_data?autoReconnect=true&useSSL=false
    username : root
    password : 

  http : 
    encoding :  
      charset : UTF-8
      enabled : true
      force : true

  mail : 
    host : localhost
    port : 25

logging : 
  file : c:\\temp\\gestecole.log
  level.org.springframework.data : DEBUG


gestecole :
  mail : 
    reply-to-address : no-reply@lepellerin-ecole.fr
